'use client';
import { NodeViewWrapper, type NodeViewProps } from '@tiptap/react';
import { useMemo, useRef, useState } from 'react';
import { createPortal } from 'react-dom';
import { Eye, EyeOff, Plus, RotateCcw, SlidersHorizontal, X } from 'lucide-react';
import { curveColors, numericBound, sampleCurve, type CurveMode } from '@/lib/editor/graph';
export default function GraphView({ node, updateAttributes, editor }: NodeViewProps) {
    const [open, setOpen] = useState(false), [root, setRoot] = useState<Element | null>(null);
    const [point, setPoint] = useState<[number, number] | null>(null);
    const target = useRef<HTMLDivElement>(null);
    const attrs = node.attrs;
    const expressions: string[] = (Array.isArray(attrs.expressions) ? attrs.expressions : ['x^2']).slice(0, 6);
    const modes: CurveMode[] = attrs.modes || [], hidden: boolean[] = attrs.hidden || [];
    const xMin = Number(attrs.xMin) || -10, xMax = Number(attrs.xMax) > xMin ? Number(attrs.xMax) : xMin + 20;
    const yMin = Number.isFinite(Number(attrs.yMin)) ? Number(attrs.yMin) : -5, yMax = Number(attrs.yMax) > yMin ? Number(attrs.yMax) : yMin + 10;
    const width = 800, height = Math.max(240, Math.min(560, Number(attrs.height) || 340)), left = 48, right = width - 20, top = 20, bottom = height - 36;
    const equal = attrs.equalScaling;
    const ySpan = equal ? (xMax - xMin) * (bottom - top) / (right - left) : yMax - yMin;
    const yCenter = (yMin + yMax) / 2, lowY = yCenter - ySpan / 2, highY = yCenter + ySpan / 2;
    const sx = (x: number) => left + (x - xMin) * (right - left) / (xMax - xMin), sy = (y: number) => bottom - (y - lowY) * (bottom - top) / ySpan;
    const curves = useMemo(() => expressions.map((expression, index) => {
        if (hidden[index] || !expression.trim()) return { points: [], error: '' };
        try { return { points: sampleCurve(expression, modes[index] || 'function', expressions, xMin, xMax), error: '' }; }
        catch (error) { return { points: [], error: error instanceof Error ? error.message : 'Invalid expression' }; }
    }), [attrs.expressions, attrs.modes, attrs.hidden, xMin, xMax]); // eslint-disable-line react-hooks/exhaustive-deps
    const changeRow = (index: number, expression: string) => updateAttributes({ expressions: expressions.map((value, i) => i === index ? expression.slice(0, 160) : value) });
    const removeRow = (index: number) => updateAttributes({ expressions: expressions.filter((_, i) => i !== index), modes: modes.filter((_, i) => i !== index), hidden: hidden.filter((_, i) => i !== index) });
    const ticks = (min: number, max: number) => { const raw = (max - min) / 8, magnitude = 10 ** Math.floor(Math.log10(raw)), step = [1, 2, 5, 10].map(value => value * magnitude).find(value => value >= raw) || raw; const values: number[] = []; for (let value = Math.ceil(min / step) * step; value <= max && values.length < 24; value += step) values.push(Math.abs(value) < 1e-9 ? 0 : value); return values; };
    const path = (points: [number, number][]) => { let result = '', previousY: number | null = null; for (const [x, y] of points) { const screenY = sy(y); if (!Number.isFinite(y) || Math.abs(screenY) > height * 10) { previousY = null; continue; } result += `${previousY === null || Math.abs(screenY - previousY) > height * 1.5 ? 'M' : 'L'}${sx(x).toFixed(2)},${screenY.toFixed(2)}`; previousY = screenY; } return result; };
    const pan = useRef<{ x: number; y: number } | null>(null);
    return <NodeViewWrapper className={`graph-block ${open ? 'is-editing' : ''}`} contentEditable={false}>
        <div ref={target} className="graph-target">
            <svg viewBox={`0 0 ${width} ${height}`} role="img" aria-label="Function plot with x and y axes" onPointerDown={event => { pan.current = { x: event.clientX, y: event.clientY }; event.currentTarget.setPointerCapture(event.pointerId); }} onPointerUp={event => { if (!pan.current || !editor.isEditable) return; const rect = event.currentTarget.getBoundingClientRect(); const dx = (event.clientX - pan.current.x) / rect.width * (xMax - xMin), dy = (event.clientY - pan.current.y) / rect.height * ySpan; pan.current = null; if (Math.abs(dx) + Math.abs(dy) > .01) updateAttributes({ xMin: xMin - dx, xMax: xMax - dx, yMin: yMin + dy, yMax: yMax + dy }); }} onPointerMove={event => { const rect = event.currentTarget.getBoundingClientRect(), x = xMin + ((event.clientX - rect.left) / rect.width * width - left) / (right - left) * (xMax - xMin); const curve = curves.find(item => item.points.length); if (curve) setPoint(curve.points[Math.max(0, Math.min(curve.points.length - 1, Math.round((x - xMin) / (xMax - xMin) * (curve.points.length - 1))))]); }} onPointerLeave={() => setPoint(null)}>
                <defs><clipPath id={`plot-${node.attrs.plotId || 'area'}`}><rect x={left} y={top} width={right - left} height={bottom - top}/></clipPath></defs>
                {ticks(xMin, xMax).map(x => <g key={`x${x}`}>{attrs.showGrid !== false && <line className="plot-grid" x1={sx(x)} x2={sx(x)} y1={top} y2={bottom}/>}<text className="plot-label" x={sx(x)} y={height - 12} textAnchor="middle">{Number(x.toPrecision(3))}</text></g>)}
                {ticks(lowY, highY).map(y => <g key={`y${y}`}>{attrs.showGrid !== false && <line className="plot-grid" x1={left} x2={right} y1={sy(y)} y2={sy(y)}/>}<text className="plot-label" x={left - 10} y={sy(y) + 4} textAnchor="end">{Number(y.toPrecision(3))}</text></g>)}
                {attrs.showAxes !== false && <g className="plot-axes"><line x1={left} x2={right} y1={sy(Math.max(lowY, Math.min(highY, 0)))} y2={sy(Math.max(lowY, Math.min(highY, 0)))}/><line x1={sx(Math.max(xMin, Math.min(xMax, 0)))} x2={sx(Math.max(xMin, Math.min(xMax, 0)))} y1={top} y2={bottom}/><text x={right - 4} y={sy(Math.max(lowY, Math.min(highY, 0))) - 8}>x</text><text x={sx(Math.max(xMin, Math.min(xMax, 0))) + 9} y={top + 10}>y</text></g>}
                <g clipPath={`url(#plot-${node.attrs.plotId || 'area'})`}>{curves.map((curve, index) => <path className="plot-curve" key={index} d={path(curve.points)} stroke={curveColors[index]} />)}{(attrs.points || []).slice(0, 100).map(([x, y]: number[], index: number) => <circle key={index} cx={sx(x)} cy={sy(y)} r="4" fill={curveColors[index % 6]}/>)}{point && attrs.showPointValues !== false && Number.isFinite(point[1]) && <g><circle cx={sx(point[0])} cy={sy(point[1])} r="4" fill="var(--ink)"/><text className="plot-label" x={Math.min(right - 100, sx(point[0]) + 9)} y={Math.max(top + 12, sy(point[1]) - 12)}>({point[0].toFixed(2)}, {point[1].toFixed(2)})</text></g>}</g>
            </svg>
            {curves.some(curve => curve.error) && <div className="graph-error">{curves.filter(curve => curve.error).map(curve => curve.error).join(' · ')}</div>}
        </div>
        <div className="graph-actions"><div className="graph-legend">{attrs.showLegend !== false && expressions.map((expression, index) => !hidden[index] && <span key={index}><i style={{ background: curveColors[index] }}/>{modes[index] === 'derivative' ? 'd/dx ' : modes[index] === 'primitive' ? '∫ ' : ''}{expression}</span>)}</div>{editor.isEditable && <button aria-label="Edit graph" onClick={() => { setRoot(target.current?.closest('.lemma-app') || document.body); setOpen(!open); }}><SlidersHorizontal size={13}/> Edit graph</button>}</div>
        {open && root && createPortal(<aside className="graph-inspector" role="dialog" aria-label="Graph composer" onKeyDown={event => { if (event.key === 'Escape') setOpen(false); event.stopPropagation(); }}>
            <div className="history-head"><h2>Graph composer</h2><div><button aria-label="Reset graph viewport" onClick={() => updateAttributes({ xMin: -10, xMax: 10, yMin: -5, yMax: 5 })}><RotateCcw size={15}/></button><button aria-label="Close graph composer" onClick={() => setOpen(false)}><X size={17}/></button></div></div>
            <h3>Expressions</h3><div className="expression-list">{expressions.map((expression, index) => <div className="expression-row" key={index}><i style={{ background: curveColors[index] }}/><input aria-label={`Expression ${index + 1}`} value={expression} placeholder="f(x) = sin(x)" onChange={event => changeRow(index, event.target.value)}/><button aria-label={`${hidden[index] ? 'Show' : 'Hide'} expression ${index + 1}`} onClick={() => updateAttributes({ hidden: expressions.map((_, i) => i === index ? !hidden[i] : !!hidden[i]) })}>{hidden[index] ? <EyeOff size={14}/> : <Eye size={14}/>}</button><button aria-label={`Remove expression ${index + 1}`} onClick={() => removeRow(index)}><X size={14}/></button><select aria-label={`Plot operation ${index + 1}`} value={modes[index] || 'function'} onChange={event => updateAttributes({ modes: expressions.map((_, i) => i === index ? event.target.value : modes[i] || 'function') })}><option value="function">Function</option><option value="derivative">Derivative · d/dx</option><option value="primitive">Primitive · ∫, F(0) = 0</option></select>{curves[index]?.error && <small>{curves[index].error}</small>}</div>)}</div>
            <button className="add-expression" disabled={expressions.length >= 6} onClick={() => updateAttributes({ expressions: [...expressions, ''], modes: [...expressions.map((_, i) => modes[i] || 'function'), 'function'], hidden: [...expressions.map((_, i) => !!hidden[i]), false] })}><Plus size={14}/> Add expression</button>
            <h3>Viewport</h3><div className="graph-viewport">{(['xMin', 'xMax', 'yMin', 'yMax'] as const).map(key => <label key={`${key}-${attrs[key]}`}>{key[0]} {key.endsWith('Min') ? 'min' : 'max'}<input aria-label={`Graph ${key[0]} ${key.endsWith('Min') ? 'minimum' : 'maximum'}`} defaultValue={attrs[key]} onBlur={event => updateAttributes({ [key]: numericBound(event.target.value, Number(attrs[key])) })} onKeyDown={event => { if (event.key === 'Enter') event.currentTarget.blur(); }}/></label>)}</div>
            <h3>Plot options</h3><div className="plot-options">{[['showGrid', 'Show grid'], ['showAxes', 'Show axes'], ['showLegend', 'Show legend'], ['equalScaling', 'Equal scaling'], ['showPointValues', 'Show point values']].map(([key, label]) => <label key={key}><input type="checkbox" checked={key === 'equalScaling' ? !!attrs[key] : attrs[key] !== false} onChange={event => updateAttributes({ [key]: event.target.checked })}/>{label}</label>)}</div>
            <label className="graph-height">Height<input aria-label="Graph height" type="range" min="240" max="560" step="20" value={height} onChange={event => updateAttributes({ height: +event.target.value })}/></label>
            <div className="graph-point-manager"><strong>Points</strong><button onClick={() => { const coords = window.prompt('Coordinates: x, y'); if (!coords) return; const pair = coords.split(',').map(Number); if (pair.length === 2 && pair.every(Number.isFinite)) updateAttributes({ points: [...(attrs.points || []).slice(0, 99), pair] }); }}><Plus size={13}/> Add point</button>{(attrs.points || []).slice(0, 100).map(([x, y]: number[], index: number) => <span key={index}>({x}, {y})<button aria-label={`Remove point ${x}, ${y}`} onClick={() => updateAttributes({ points: attrs.points.filter((_: number[], i: number) => i !== index) })}><X size={12}/></button></span>)}</div>
            <small className="settings-hint">Derivatives and primitives use numerical approximation. Drag to pan.</small><button className="inspector-done" onClick={() => setOpen(false)}>Done</button>
        </aside>, root)}
    </NodeViewWrapper>;
}
