'use client';
import { useState } from 'react';
import { FileText, BookOpen, Sigma, Calculator, GraduationCap, Atom, Code2, FlaskConical, Pencil, Lightbulb, Bookmark, Star, Heart, Globe, Music, Folder, Hash, Brain, Library, Target, type LucideIcon } from 'lucide-react';
import Overlay from './Overlay';
export const documentIcons: Record<string, LucideIcon> = { document: FileText, book: BookOpen, math: Sigma, calculator: Calculator, course: GraduationCap, atom: Atom, code: Code2, science: FlaskConical, pencil: Pencil, idea: Lightbulb, bookmark: Bookmark, star: Star, heart: Heart, globe: Globe, music: Music, folder: Folder, hash: Hash, brain: Brain, library: Library, target: Target };
const emojis = [['📘', 'book'], ['📝', 'notes'], ['📐', 'geometry'], ['🧮', 'math'], ['🔬', 'science'], ['⚛️', 'physics'], ['💻', 'computer'], ['🧠', 'brain'], ['💡', 'idea'], ['🎓', 'course'], ['🌍', 'world'], ['📊', 'statistics'], ['⭐', 'star'], ['🎵', 'music'], ['❤️', 'heart'], ['🔖', 'bookmark'], ['📚', 'library'], ['🎯', 'target'], ['✨', 'sparkles'], ['🧪', 'chemistry'], ['🚀', 'rocket'], ['🌱', 'nature'], ['🗂️', 'folder'], ['🔢', 'numbers'], ['🌀', 'spiral'], ['☀️', 'sun'], ['🌙', 'moon'], ['🎨', 'art'], ['⚡', 'energy'], ['🏛️', 'history']];
export function DocumentIcon({ value, size = 18 }: { value?: string | null; size?: number }) { const Icon = documentIcons[value || 'document']; return Icon ? <Icon size={size}/> : <span className="document-emoji" style={{ fontSize: size }}>{value}</span>; }
export default function IconPicker({ onSelect, onClose }: { onSelect: (value: string) => void; onClose: () => void }) {
    const [tab, setTab] = useState('icons'), [query, setQuery] = useState('');
    return <Overlay onClose={onClose}><section className="icon-picker" role="dialog" aria-label="Document icon"><header><button aria-pressed={tab === 'emoji'} onClick={() => setTab('emoji')}>Emoji</button><button aria-pressed={tab === 'icons'} onClick={() => setTab('icons')}>Icons</button><button className="icon-reset" onClick={() => { onSelect('document'); onClose(); }}>Reset</button></header><input autoFocus aria-label="Filter icons" placeholder="Filter icons…" value={query} onChange={event => setQuery(event.target.value)}/><div className="icon-picker-grid">{tab === 'icons' ? Object.entries(documentIcons).filter(([name]) => name.includes(query.toLowerCase())).map(([name, Icon]) => <button aria-label={`${name} icon`} key={name} onClick={() => { onSelect(name); onClose(); }}><Icon size={25}/></button>) : emojis.filter(([, name]) => name.includes(query.toLowerCase())).map(([emoji, name]) => <button aria-label={`${name} emoji`} key={name} onClick={() => { onSelect(emoji); onClose(); }}>{emoji}</button>)}</div></section></Overlay>;
}
