'use client';
import { Node, mergeAttributes, ReactNodeViewRenderer, NodeViewWrapper, type NodeViewProps } from '@tiptap/react';
import { useEffect, useRef, useState } from 'react';
import katex from 'katex';
import 'katex/dist/katex.min.css';
import functionPlot from 'function-plot';
import { snippets, expand } from '@/lib/editor/snippets';

function renderLatex(source: string, displayMode: boolean) { try { return katex.renderToString(source || '\\;',{displayMode,throwOnError:false,trust:false,strict:'ignore'}); } catch { return ''; } }
const graphColors=['#3478d4','#d45555','#3a9b72','#955ec7','#db8d2e','#2797a4'];
function EquationView({node,updateAttributes}:NodeViewProps) {
 const [editing,setEditing]=useState(false); const [value,setValue]=useState(String(node.attrs.latex||'')); const [query,setQuery]=useState(''); const [suggestIndex,setSuggestIndex]=useState(0); const [fields,setFields]=useState<[number,number][]>([]); const [fieldIndex,setFieldIndex]=useState(0); const input=useRef<HTMLTextAreaElement>(null); const matches=snippets.filter(s=>s.label.toLowerCase().startsWith(query.toLowerCase()));
 const beginEdit=()=>{setValue(String(node.attrs.latex||''));setEditing(true)};
 const block=node.type.name==='mathBlock'; const EditorShell=block?'div':'span'; const LabelRow=block?'div':'span'; const Preview=block?'div':'span';
 return <NodeViewWrapper as={block?'div':'span'} className={block?'equation-wrap':'inline-equation-wrap'}>
  {editing ? <EditorShell className={block?'equation-editor':'inline-equation-editor'} contentEditable={false}>
   <LabelRow className="equation-editor-label"><span>LATEX</span><span>PREVIEW</span></LabelRow>
   <textarea ref={input} autoFocus value={value} onChange={e=>{const next=e.target.value;setValue(next);const before=next.slice(0,e.target.selectionStart);const match=before.match(/\\([a-zA-Z]*)$/);setQuery(match&&match[1]?`\\${match[1]}`:'');setSuggestIndex(0)}} onKeyDown={e=>{if(query&&matches.length&&(e.key==='Enter'||e.key==='Tab')){e.preventDefault();const before=value.slice(0,e.currentTarget.selectionStart);const match=before.match(/\\([a-zA-Z]*)$/);const start=match?e.currentTarget.selectionStart-match[0].length:e.currentTarget.selectionStart;const expanded=expand(matches[suggestIndex].template,start);const after=value.slice(e.currentTarget.selectionEnd);const next=value.slice(0,start)+expanded.text+after;setValue(next);setQuery('');setFields(expanded.fields);setFieldIndex(0);requestAnimationFrame(()=>{input.current?.focus();if(expanded.fields.length)input.current?.setSelectionRange(...expanded.fields[0]);else input.current?.setSelectionRange(start+expanded.text.length,start+expanded.text.length)});return}if(query&&matches.length&&e.key==='ArrowDown'){e.preventDefault();setSuggestIndex(i=>Math.min(i+1,matches.length-1));return}if(query&&matches.length&&e.key==='ArrowUp'){e.preventDefault();setSuggestIndex(i=>Math.max(0,i-1));return}if(fields.length&&e.key==='Tab'){e.preventDefault();const next=(fieldIndex+1)%fields.length;setFieldIndex(next);input.current?.setSelectionRange(...fields[next]);return}if(e.key==='Escape'){e.preventDefault();setEditing(false);} if(e.key==='Enter'&&(e.metaKey||e.ctrlKey)){e.preventDefault();updateAttributes({latex:value});setEditing(false);}}} placeholder="Type a mathematical expression…" />
   {query&&matches.length>0&&<div className="latex-suggestions">{matches.slice(0,5).map((item,index)=><button type="button" key={item.label} className={index===suggestIndex?'active':''} onMouseDown={e=>{e.preventDefault();const caret=input.current?.selectionStart||value.length;const before=value.slice(0,caret);const match=before.match(/\\([a-zA-Z]*)$/);const start=match?caret-match[0].length:caret;const expanded=expand(item.template,start);const next=value.slice(0,start)+expanded.text+value.slice(input.current?.selectionEnd||caret);setValue(next);setQuery('');setFields(expanded.fields);requestAnimationFrame(()=>{input.current?.focus();if(expanded.fields.length)input.current?.setSelectionRange(...expanded.fields[0])})}}><code>{item.label}</code><span>{item.template.replace(/[«»]/g,'')}</span></button>)}</div>}
   <Preview className="equation-live-preview" dangerouslySetInnerHTML={{__html:renderLatex(value,block)}} />
   <button className="equation-done" onClick={()=>{updateAttributes({latex:value});setEditing(false);}}>Done <kbd>⌘ ↵</kbd></button>
  </EditorShell> : <span className={block?'equation-render':'inline-equation-render'} onClick={beginEdit}>{node.attrs.latex? <span dangerouslySetInnerHTML={{__html:renderLatex(String(node.attrs.latex),block)}}/> : <span className="equation-placeholder">{block?'Click to write an equation…':'∑ add inline equation'}</span>}</span>}
 </NodeViewWrapper>
}
export const MathBlock=Node.create({name:'mathBlock',group:'block',atom:true,isolating:true,addAttributes(){return {latex:{default:''}}},parseHTML(){return [{tag:'div[data-type="math-block"]'}]},renderHTML({HTMLAttributes}){return ['div',mergeAttributes(HTMLAttributes,{'data-type':'math-block','data-latex':HTMLAttributes.latex})]},addNodeView(){return ReactNodeViewRenderer(EquationView)}});
export const InlineMath=Node.create({name:'inlineMath',group:'inline',inline:true,atom:true,selectable:true,addAttributes(){return {latex:{default:''}}},parseHTML(){return [{tag:'span[data-type="inline-math"]'}]},renderHTML({HTMLAttributes}){return ['span',mergeAttributes(HTMLAttributes,{'data-type':'inline-math','data-latex':HTMLAttributes.latex})]},addNodeView(){return ReactNodeViewRenderer(EquationView)}});
export const PageBreak=Node.create({name:'pageBreak',group:'block',atom:true,selectable:true,addAttributes(){return {number:{default:2},spacer:{default:1171}}},parseHTML(){return [{tag:'div[data-type="page-break"]'}]},renderHTML({HTMLAttributes}){return ['div',mergeAttributes(HTMLAttributes,{'data-type':'page-break','data-page':HTMLAttributes.number,style:`height:${HTMLAttributes.spacer}px`})]}});
function GraphView({node,updateAttributes}:NodeViewProps){
 const target=useRef<HTMLDivElement>(null); const [open,setOpen]=useState(false); const expr=(node.attrs.expressions as string[])||['x^2']; const points=(node.attrs.points as number[][])||[]; const expressionsKey=expr.join('|');const pointsKey=JSON.stringify(points);
 useEffect(()=>{if(!target.current)return; try {const plotPoints=JSON.parse(pointsKey) as number[][];functionPlot({target:target.current,width:Math.max(300,target.current.clientWidth||640),height:Number(node.attrs.height)||320,grid:true,disableZoom:false,xAxis:{domain:[Number(node.attrs.xMin)||-10,Number(node.attrs.xMax)||10]},data:[...expressionsKey.split('|').filter(Boolean).map((fn,index)=>({fn,graphType:'polyline' as const,color:graphColors[index%graphColors.length]})),...plotPoints.map((point,index)=>({fnType:'points' as const,graphType:'scatter' as const,points:[point],color:graphColors[index%graphColors.length]}))]});}catch{target.current.innerHTML='<span class="graph-error">Could not plot that expression.</span>'}},[expressionsKey,pointsKey,node.attrs.xMin,node.attrs.xMax,node.attrs.height]);
 return <NodeViewWrapper className="graph-block" contentEditable={false}><div ref={target} className="graph-target"/><div className="graph-actions"><span>Drag to pan · scroll to zoom · hover to read coordinates</span><button onClick={()=>setOpen(!open)}>{open?'Done':'Edit graph'}</button></div>{open&&<div className="graph-settings"><label>Functions · one per line<textarea rows={Math.min(5,Math.max(2,expr.length))} value={expr.join('\n')} onChange={e=>updateAttributes({expressions:e.target.value.split(/[\n,]/).map(s=>s.trim()).filter(Boolean)})}/></label><label>From<input type="number" value={node.attrs.xMin} onChange={e=>updateAttributes({xMin:+e.target.value})}/></label><label>To<input type="number" value={node.attrs.xMax} onChange={e=>updateAttributes({xMax:+e.target.value})}/></label><label>Height<input type="range" min="240" max="560" step="20" value={node.attrs.height||320} onChange={e=>updateAttributes({height:+e.target.value})}/></label><div className="graph-point-manager"><strong>Points</strong><button onClick={()=>{const coords=window.prompt('Enter coordinates as x, y');if(!coords)return;const [x,y]=coords.split(',').map(Number);if(Number.isFinite(x)&&Number.isFinite(y))updateAttributes({points:[...points,[x,y]]})}}>+ Add point</button>{points.map(([x,y],index)=><span key={`${x}-${y}-${index}`}>({x}, {y}) <button title="Remove point" onClick={()=>updateAttributes({points:points.filter((_,i)=>i!==index)})}>×</button></span>)}</div></div>}</NodeViewWrapper>
}
export const Graph=Node.create({name:'graph',group:'block',atom:true,addAttributes(){return {expressions:{default:['x^2']},points:{default:[]},xMin:{default:-10},xMax:{default:10},height:{default:320}}},parseHTML(){return [{tag:'div[data-type="graph"]'}]},renderHTML({HTMLAttributes}){return ['div',mergeAttributes(HTMLAttributes,{'data-type':'graph'})]},addNodeView(){return ReactNodeViewRenderer(GraphView)}});
export const Callout=Node.create({name:'callout',group:'block',content:'block+',defining:true,parseHTML(){return [{tag:'aside[data-type="callout"]'}]},renderHTML({HTMLAttributes}){return ['aside',mergeAttributes(HTMLAttributes,{'data-type':'callout'}),0]}});
